apiVersion: apps/v1
kind: Deployment
metadata:
  name: tweetservice-deployment
  labels:
    app: tweetservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tweetservice
  template:
    metadata:
      labels:
        app: tweetservice
    spec:
      containers:
        - name: tweetservice
          imagePullPolicy: Always
          image: imadelfetouh99/tweetservice:latest
          ports:
            - containerPort: 8082
          env:
            - name: TWEETSERVICE_MYSQL_MASTER_HOST
              value: mysql-tweetservice-master-service
            - name: TWEETSERVICE_MYSQL_REPLICA_HOST
              value: mysql-tweetservice-replica-service
            - name: TWEETSERVICE_MYSQL_MASTER_PORT
              value: '3306'
            - name: TWEETSERVICE_MYSQL_REPLICA_PORT
              value: '3308'
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PASS
              value: imad
---
apiVersion: v1
kind: Service
metadata:
  name: tweetservice-service
spec:
  selector:
    app: tweetservice
  type: LoadBalancer
  ports:
    - port: 8082
      targetPort: 8082